// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _extauth from "./ext/auth";
export type $Player_statsλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "id_room": $.PropertyDesc<_std.$uuid, $.Cardinality.One, false, false, false, false>;
  "id_user": $.PropertyDesc<_std.$uuid, $.Cardinality.One, false, false, false, false>;
  "score": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
}>;
type $Player_stats = $.ObjectType<"default::Player_stats", $Player_statsλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Player_stats = $.makeType<$Player_stats>(_.spec, "d84ce3aa-115b-11ef-82af-558d60e14cb9", _.syntax.literal);

const Player_stats: $.$expr_PathNode<$.TypeSet<$Player_stats, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Player_stats, $.Cardinality.Many), null);

export type $RoomλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "delay": $.PropertyDesc<_std.$int32, $.Cardinality.One, false, false, false, false>;
  "latitude": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "longitude": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "nb_players": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, false>;
  "prompt": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Room = $.ObjectType<"default::Room", $RoomλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Room = $.makeType<$Room>(_.spec, "d84ef1ad-115b-11ef-b781-f39d1b1b077d", _.syntax.literal);

const Room: $.$expr_PathNode<$.TypeSet<$Room, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Room, $.Cardinality.Many), null);

export type $Temp_roomλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "id_room": $.PropertyDesc<_std.$uuid, $.Cardinality.One, false, false, false, false>;
  "id_user": $.PropertyDesc<_std.$uuid, $.Cardinality.One, false, false, false, false>;
  "latitude": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "longitude": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "time": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, false>;
}>;
type $Temp_room = $.ObjectType<"default::Temp_room", $Temp_roomλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Temp_room = $.makeType<$Temp_room>(_.spec, "d850eea8-115b-11ef-a549-2bef327fa414", _.syntax.literal);

const Temp_room: $.$expr_PathNode<$.TypeSet<$Temp_room, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Temp_room, $.Cardinality.Many), null);

export type $UsersλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "identity": $.LinkDesc<_extauth.$Identity, $.Cardinality.One, {}, true, false,  false, false>;
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "full_name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "nationality": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "pseudo": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "avatar": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "score": $.PropertyDesc<_std.$int16, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $Users = $.ObjectType<"default::Users", $UsersλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {identity: {__element__: _extauth.$Identity, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Users = $.makeType<$Users>(_.spec, "d852c374-115b-11ef-b7b7-d52fe695dec0", _.syntax.literal);

const Users: $.$expr_PathNode<$.TypeSet<$Users, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Users, $.Cardinality.Many), null);

export type $current_userλShape = $.typeutil.flatten<$UsersλShape & {
}>;
type $current_user = $.ObjectType<"default::current_user", $current_userλShape, null, [
  ...$Users['__exclusives__'],
]>;
const $current_user = $.makeType<$current_user>(_.spec, "d912bc18-115b-11ef-a2df-51c3973aa19a", _.syntax.literal);

const current_user: $.$expr_PathNode<$.TypeSet<$current_user, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($current_user, $.Cardinality.Many), null);

const $default__globals: {  current_user: _.syntax.$expr_Global<
              // "default::current_user",
              $current_user,
              $.Cardinality.AtMostOne
              >} = {  current_user: _.syntax.makeGlobal(
              "default::current_user",
              $.makeType(_.spec, "d912bc18-115b-11ef-a2df-51c3973aa19a", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { $Player_stats, Player_stats, $Room, Room, $Temp_room, Temp_room, $Users, Users, $current_user, current_user };

type __defaultExports = {
  "Player_stats": typeof Player_stats;
  "Room": typeof Room;
  "Temp_room": typeof Temp_room;
  "Users": typeof Users;
  "current_user": typeof current_user;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "Player_stats": Player_stats,
  "Room": Room,
  "Temp_room": Temp_room,
  "Users": Users,
  "current_user": current_user,
  "global": $default__globals
};
export default __defaultExports;
