import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from '@nextui-org/react'
import "./globals.css";
import Footer from "@/components/landing/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Enigmap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <NextUIProvider>
        <body className={inter.className}>
          <main className="px-[2%] py-3">
            {children}
          </main>
        </body>
        <footer>
          <Footer />
        </footer>
      </NextUIProvider>
    </html>
  );
}
