import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Navbar from "@/components/game/Navbar"
import { auth } from "@/edgedb"
import { redirect } from "next/navigation"
import { cookies } from "next/headers"
import UserAction from "@/services/user-action"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: "Enigmap",
    description: "Generated by create next app",
}

export default async function GameLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    const session = auth.getSession()
    if ((await session.isSignedIn()) == false) {
        redirect("/")
    }

    const identityCookie = cookies().get("identity")?.value as string
    const identity = identityCookie.replace(/"/g, "")
    const user = await UserAction.getData(identity)
    return (
        <div>
            <Navbar user={{ id: identity, ...user }} />
            {children}
        </div>
    )
}
